export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_CATEGORIES_ERROR = "GET_ALL_CATEGORIES_ERROR";
export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_ALL_QUESTIONS_ERROR = "GET_ALL_QUESTIONS_ERROR";
export const SAVE_FEEDBACK = "SAVE_FEEDBACK";
export const SAVE_FEEDBACK_ERROR = "SAVE_FEEDBACK_ERROR";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_ERROR = "GET_ALL_USERS_ERROR";
